### ISSUE TITLE
Выделить активные вакансии в списке

### ISSUE THREAD

**Issue by orestx** [msp4/client#49]
![image](https://cloud.githubusercontent.com/assets/2162824/6664559/9b2b3e2e-cbd9-11e4-9885-200f010438fb.png)

Предлагаю как то выделить активные вакансии от остальных (по моему цветных ярлыков не достаточно как сейчас).
Например, можно сделать все тексты в закрытых вакансиях - курсивом:
![image](https://cloud.githubusercontent.com/assets/2162824/6664661/6cde9434-cbda-11e4-9a74-7d81ccc1d31f.png)

Хотя может даже одного курсива мало. Можно еще высветлить тексты:
![image](https://cloud.githubusercontent.com/assets/2162824/6664718/dbf3af6c-cbda-11e4-9e61-32ba8a8ac3a3.png)

**Comment by orestx** [comment]
good

**Comment by orestx** [comment]
not good.

Выполняется != закрытая.
Сделай ее так же как активные.
![image](https://cloud.githubusercontent.com/assets/2162824/9681278/87b68cd2-5305-11e5-91c2-16b1cbffa367.png)

**Comment by vladmokryi** [comment]
@orest синим?

**Comment by orestx** [comment]
Нет. Чему посвящалась эта задача?
Убрать курсив и сделать цвет нормальным (если делалось что то еще, то и оно должно быть исправленным). В общем все что сделал что бы отделить неактивные от активных.

**Comment by vladmokryi** [comment]
Сделал

**Comment by vladmokryi** [comment]
и "на доработке" != закрытая
добавил к активным

**Comment by orestx** [comment]
>и "на доработке" != закрытая

угу, правильно.

В общем, вродь норм.
