### ISSUE TITLE
Нужно убрать тестовые анкеты

### ISSUE THREAD

**Issue by orestx** [msp4/client#61]
![image](https://cloud.githubusercontent.com/assets/2162824/9272072/98377942-4287-11e5-9087-a59c42ac2182.png)

@Iryna-Ivasko Посмотри пожалуйста список, могут быть названия типа тест но с нормальным содержимым(тогда если нужно сохрани для себя данные или если полностью сохранится анкета то переименуй ее). А что удалить - направь задачу на @vladmokryi  что бы удалил лишние.

**Comment by vladmokryi** [comment]
Делаю таску по копированию анкет + удаление , думаю сегодня закончу и это можно будет сделать в manager

**Comment by Iryna-Ivasko** [comment]
Посмотрела, все анкеты с именем "test, test1, тест" или полностью с пустой строкой названия могут быть смело удалены.

**Comment by vladmokryi** [comment]
Почистил, на manager добавлен функционал по удалению анкет
