### ISSUE TITLE
Удаление заявок при деактивации вакансии

### ISSUE THREAD

**Issue by vladmokryi** [msp4/client#71]
Когда переводишь вакансию в неактивную заявки которые присылали шоперы оставались в статусе new и показывались шоперам как и до деактивации
Добавил hook при редактировании вакансии, который пробегается по заявкам и переводит их в статус "cancelled"

**Comment by orestx** [comment]
Поздравляю. У тебя родился очередной миленький бажик :)
После того как вакансию отменили - заявка у тпшника сбросилась, это хорошо. Но когда вакансию снова активировали:
1. В списке рекомендованных она уже не появилась.
2. На странице поиска вакансий я ее вижу, но вижу с отметкой, что я подал на нее заявку, а должна быть сброшенной.
3. Когда я на нее кликаю - вижу что у меня нет кнопки "отказаться от вакансии":
![image](https://cloud.githubusercontent.com/assets/2162824/9682027/7ef65cfc-530b-11e5-86e5-02d374563804.png)

4. Когда вакансию отменили, я не должен видеть ее, перейдя по прямой ссылке.
5. Когда клиент отменяет вакансию, но есть на нее заявки - нужно показывать ему модальное окно с сообщением что все заявки будут сброшены и кнопки ок/отменить

Не буду утверждать что все это - результат твоих правок, но в любом случае некоторые пункты связаны и нужно подправить...

**Comment by vladmokryi** [comment]
![image](https://cloud.githubusercontent.com/assets/13148141/9689403/791bd388-533e-11e5-9355-c90547c1907d.png)
@alexzaporozhets @orestx 
модальное окно такого содержания?

**Comment by vladmokryi** [comment]
или так
![image](https://cloud.githubusercontent.com/assets/13148141/9689801/1213e772-5341-11e5-997f-39f2d62ab041.png)

**Comment by vladmokryi** [comment]
и еще
возможно нужно при деактивации вакансии удалять заявки
*во 1 зачем хранить мусор
*во 2 как я понял от 1 шопера только 1 заявка
*в 3 если сбрасывать настройки заявки, она всеравно останется привазяной к шоперу

**Comment by orestx** [comment]
По поводу деактивации вакансии. Нужно что бы все такие уведомления были по одному шаблону, одинаковые стили. Я сравнил,например, с сообщением об удалении исследования, там тоже есть уточняющая информация. Предлагаю взять ее запример.
Если сравнить с твоими вариантами, то получается второй вариант, только там нет иконки как у тебя. С иконкой тож неплохо смотрится, но давай пока без нее, только я конкретные стили не сравнивал, а только на глаз. Сделай что бы было в одинаковом формате.
Так же по поводу текста на кнопках этого сообщения. Давай вместо ок напишем продолжить.

**Comment by orestx** [comment]
>возможно нужно при деактивации вакансии удалять заявки

а я об этом писал:
>2.На странице поиска вакансий я ее вижу, но вижу с отметкой, что я подал на нее заявку, а должна быть сброшенной.

**Comment by vladmokryi** [comment]
Сделал, кнопку "отказатся" тоже добавил на шопере

**Comment by orestx** [comment]
теперь все ок
