### ISSUE TITLE
Поменять текст в корзине

### ISSUE THREAD

**Issue by orestx** [msp4/client#72]
Нужно оставить текст "деньги блокируются..." только вверху, а нижнюю копию убрать.
Так же нужно заменить тот текст на такой:
Если ТП не выполнит задание, ваши средства будут возвращены

![image](https://cloud.githubusercontent.com/assets/2162824/9681124/6b3e19b8-5304-11e5-9814-8b200b0c010a.png)

**Comment by alexzaporozhets** [comment]
@orestx текст ты сам поменять можешь

**Comment by orestx** [comment]
Могу, но я буду настраивать рабочее окружение дольше чем выполняется вся задача (ведь нужно же увидеть что заливаю). Человеку, который занимается этим проектом это будет стоить максимум несколько минут.
Я то могу прямо через github поправть, но не уверен что это хорошая практика...
Но ок, в этом случае риск и стоимость ошибки стремятся к нулю, так что могу и я.

**Comment by orestx** [comment]
готово
