### ISSUE TITLE
Можливість видалення дослідження в таблиці

### ISSUE THREAD

**Issue by Iryna-Ivasko** [msp4/client#78]
Щоб можна було видалити дослідження, не заходячи в локацію або в редагування.
![image](https://cloud.githubusercontent.com/assets/12249275/9734166/913aedf2-5639-11e5-88fa-d2d840bd575b.png)

**Comment by orestx** [comment]
Тут еще есть такая мысль, которую можна будет обсудить, что исследование это один из самых крупных объектов в учетной записи и включает в себя много информации. Так же, исследования не будут создаваться как по конвейеру. Я веду к тому, что может и достаточно будет удаления в настройках исследования, так как оно создается для того что бы получить информацию, позже ее можно просматривать и сравнивать, как архив. Вынесенная кнопка вреда не принесет, но в общем нужна ли - хз.

**Comment by orestx** [comment]
@chemfind как считаешь?

**Comment by alexzaporozhets** [comment]
это удобно только для тестов! если пользователь сделает ошибку - финансовые потери

**Comment by orestx** [comment]
ок, тогда отбой, эта кнопка не нужна.
